services:
  redis-server:
    image: 'redis'
    ports:
      - '6379:6379'
    # restart unless forcibly stopped
    restart: unless-stopped

  node-app:
    build: .
    depends_on:
      - redis-server
    environment:
     - PORT=${PORT}
     - REDIS_HOST=${REDIS_HOST}
     - REDIS_PORT=${REDIS_PORT}
    
    ports:
      - '80:${PORT}'
    # restart on failure (exit code != 0)
    restart: on-failure 
